name: lexical_evolution_env
dependencies:
  - python=3.11
  - jupyter
  - pip
  - r-base
  - r-essentials
  - jupyter
  - pip:
      - datasets
      - huggingface
      - circuitsvis
      - huggingface_hub
      - ipython
      - jaxtyping
      - tqdm
      - matplotlib
      - spacy
      - nbformat
      - plotly
